"""PPU ppu-llc compile-time regression guard for causal_conv1d.

Guards against SDK 2.1.1 regression #1 (internal bug report): ppu-llc
crashed with SIGABRT (return code 134) while compiling the Triton kernel
generated by causal_conv1d_update. True crash criterion, re-measured on
ppu1 on 2026-08-21:

- dtype=float32 crashes in BOTH variants (three rounds of runs all report
  1 failed, 4 passed, 1 xfailed; plain-f32 hits the same ppu-llc
  "double free or corruption" abort in two distinct temp .tix.trans files)
- fp16/bf16 compile fine in both variants

The RCA-era claim "only the batch_gather variant crashes, all 12 plain
cases compile fine" came from an upstream sweep that tested plain
causal_conv1d_update with itype=[torch.bfloat16] ONLY (test_causal_conv1d.py
sweeps bf16 alone), so float32 was never actually run through the plain
path -- it was an over-generalisation, not a measured boundary.

The upstream test registered/layers/mamba/test_causal_conv1d.py is
``disabled=`` on PPU. This native guard parametrizes the dtype x variant
matrix so the exact crash cells are pinned: the two float32 cells
(plain-f32 and batch_gather-f32) carry xfail(strict=True), so they
report xfail while the SDK bug exists and XPASS becomes a failure once
the fix lands -- that XPASS is the signal to delete the markers and
re-enable the upstream test on PPU. The other four cells (f16/bf16, both
variants) must still PASS: if the crash scope ever widens to a new
dtype the suite fails immediately instead of being discovered by
accident in nightly.

This is a COMPILE-TIME test: a cell passes when the kernel compiles and
returns a tensor of the expected shape. No numerical assertion is needed
(correctness of the compiled kernel is the upstream test's job once it is
re-enabled). Set TRITON_CACHE_DIR to a scratch directory to preserve the
.tix.trans intermediate IR for offline reproduction if a cell fails.

Usage:
python3 -m pytest test/registered/ppu/test_ppu_causal_conv1d_compile.py -v
"""

import sys

import pytest
import torch

from sglang.srt.layers.attention.mamba.causal_conv1d_triton import (
    PAD_SLOT_ID,
    causal_conv1d_update,
)
from sglang.srt.utils import get_device
from sglang.test.ci.ci_register import register_ppu_ci

register_ppu_ci(est_time=20, suite="nightly-1-ppu", nightly=True)

# The crash cell from the RCA, test id
# [3-True-2064-3-1-False-False-itype0]: batch_size=3, with_padding=True,
# dim=2064, width=3, seqlen=1, has_bias=False, silu_activation=False.
BATCH_SIZE = 3
DIM = 2064
WIDTH = 3
SEQLEN = 1


_CRASH_CELL_REASON = (
    "SDK 2.1.1 regression #1: ppu-llc SIGABRT (return code 134) compiling "
    "the float32 kernel (crashes in both the plain and batch_gather "
    "variants; re-measured on ppu1 2026-08-21). Strict xfail: when this "
    "cell starts passing (XPASS), the SDK fix has landed -- delete these "
    "markers and re-enable registered/layers/mamba/test_causal_conv1d.py "
    "on PPU."
)

# The 3x2 dtype x variant matrix as explicit cells, so the xfail markers
# can be pinned to exactly the float32 cells (both variants crash).
_CELLS = [
    pytest.param(
        "plain",
        torch.float32,
        id="plain-f32",
        marks=pytest.mark.xfail(strict=True, reason=_CRASH_CELL_REASON),
    ),
    pytest.param("plain", torch.float16, id="plain-f16"),
    pytest.param("plain", torch.bfloat16, id="plain-bf16"),
    pytest.param("batch_gather", torch.float16, id="batch_gather-f16"),
    pytest.param("batch_gather", torch.bfloat16, id="batch_gather-bf16"),
    pytest.param(
        "batch_gather",
        torch.float32,
        id="batch_gather-f32",
        marks=pytest.mark.xfail(strict=True, reason=_CRASH_CELL_REASON),
    ),
]


@pytest.mark.parametrize("variant,itype", _CELLS)
def test_causal_conv1d_update_compiles(variant, itype):
    """Every (dtype, variant) cell must compile and produce a shaped output.

    The float32 cells (both variants) are known to crash ppu-llc and are
    marked xfail(strict=True); any other cell failing here means the
    crash scope has widened beyond float32.
    """
    device = get_device()
    torch.manual_seed(0)

    weight = torch.randn(DIM, WIDTH, device=device, dtype=itype)

    if variant == "plain":
        x = torch.randn(BATCH_SIZE, DIM, SEQLEN, device=device, dtype=itype)
        conv_state = torch.randn(
            BATCH_SIZE, DIM, WIDTH - 1, device=device, dtype=itype
        )
        out = causal_conv1d_update(x, conv_state, weight, None, activation=None)
        assert out.shape == x.shape
        return

    # batch_gather variant: conv_state is a pool of cache lines addressed
    # through conv_state_indices (the gather addressing pattern whose IR
    # triggered the ppu-llc crash together with float32's wider registers).
    padding = 5
    padded_batch_size = BATCH_SIZE + padding
    total_entries = 10 * BATCH_SIZE

    x = torch.randn(
        padded_batch_size, SEQLEN, DIM, device=device, dtype=itype
    ).transpose(1, 2)
    conv_state = torch.randn(
        total_entries, WIDTH - 1, DIM, device=device, dtype=itype
    ).transpose(1, 2)
    conv_state_indices = torch.randperm(total_entries)[:BATCH_SIZE].to(
        dtype=torch.int32, device=device
    )
    padded_state_indices = torch.concat(
        [
            conv_state_indices,
            torch.as_tensor(
                [PAD_SLOT_ID] * padding, dtype=torch.int32, device=device
            ),
        ],
        dim=0,
    )

    out = causal_conv1d_update(
        x,
        conv_state,
        weight,
        None,
        activation=None,
        conv_state_indices=padded_state_indices,
        pad_slot_id=PAD_SLOT_ID,
    )
    assert out.shape == x.shape


if __name__ == "__main__":
    sys.exit(pytest.main([__file__, "-v", "-s"]))
