"""PPU NAS JIT cache reuse guard.

Guards the CI-infrastructure fix from the 2026-07-22 RCA (decision doc
section 8.1, W6-4): the tvm-ffi JIT cache is a ninja directory that
invalidates by SOURCE MTIME. The nightly ``rm -rf /workspace`` + fresh
checkout used to refresh every source mtime, making ninja do a full
recompile every night (.ninja_log rebuilt 19 days in a row). The fix pins
every file under python/sglang/jit_kernel to the HEAD commit time
(``touch -d @$(git log -1 --format=%ct)`` in the PPU workflows), so ninja
reuses the NAS-persisted cache across runs.

Two checks, matching the two criteria in the design doc:

1. Filesystem check (no GPU needed): every file under
   python/sglang/jit_kernel has mtime == HEAD commit time. This is the
   root-cause guard; without it nightly silently regresses from ~4h to ~6h.
2. Runtime check (needs a device): load the same JIT kernel in two fresh
   processes; the second load must not trigger a recompile (fast).

Usage:
python3 -m pytest test/registered/ppu/test_ppu_jit_cache_reuse.py -v
"""

import os
import subprocess
import sys
import unittest
from pathlib import Path

import torch

from sglang.test.ci.ci_register import register_ppu_ci
from sglang.test.test_utils import CustomTestCase

register_ppu_ci(est_time=15, suite="stage-b-test-1-gpu-ppu")

# test/registered/ppu/<this file> -> repo root is three levels up.
REPO_ROOT = Path(__file__).resolve().parents[3]
JIT_KERNEL_DIR = REPO_ROOT / "python" / "sglang" / "jit_kernel"

# A warm second load is interpreter startup + imports + a ninja no-op check,
# well under a minute. A full recompile of the JIT stack takes many minutes
# (the RCA measured nightly going from ~4h to ~6h), so 120s is a safe cut.
WARM_LOAD_TIMEOUT_S = 120

_LOAD_KERNEL_SNIPPET = r"""
import time
t0 = time.monotonic()
import torch
from sglang.jit_kernel.add_constant import add_constant
x = torch.arange(128, dtype=torch.float32, device="cuda")
y = add_constant(x, 3)
torch.cuda.synchronize()
assert torch.equal(y, x + 3), "add_constant produced wrong result"
print(f"JIT_LOAD_ELAPSED={time.monotonic() - t0:.2f}")
"""


class TestPPUJitCacheReuse(CustomTestCase):
    def test_jit_source_mtimes_pinned_to_head(self):
        """Criterion 1: jit_kernel sources must carry the HEAD commit mtime.

        A fresh checkout sets mtimes to checkout time, which is newer than
        every ninja cache entry -> full recompile. The workflows pin them;
        if this assertion fires, some code path started checking out or
        copying the sources without re-pinning.
        """
        try:
            out = subprocess.run(
                ["git", "-C", str(REPO_ROOT), "log", "-1", "--format=%ct"],
                capture_output=True,
                text=True,
                timeout=30,
            )
            head_ct = int(out.stdout.strip())
        except (OSError, ValueError, subprocess.TimeoutExpired):
            self.skipTest("git history unavailable; cannot verify mtime pinning")
        self.assertGreater(head_ct, 0)

        unpinned = []
        for path in sorted(JIT_KERNEL_DIR.rglob("*")):
            if not path.is_file():
                continue
            # Runtime artifacts (__pycache__/*.pyc) are regenerated by imports
            # during the suite run and are not ninja inputs; exclude them.
            if "__pycache__" in path.parts or path.suffix in (".pyc", ".pyo"):
                continue
            if int(path.stat().st_mtime) != head_ct:
                unpinned.append(
                    f"{path.relative_to(REPO_ROOT)} "
                    f"(mtime={int(path.stat().st_mtime)}, head={head_ct})"
                )
        self.assertEqual(
            unpinned,
            [],
            "jit_kernel sources not pinned to HEAD commit time; ninja will "
            "recompile the whole JIT stack on every fresh checkout "
            f"(2026-07-22 RCA). Offenders (showing up to 10): {unpinned[:10]}",
        )

    def test_jit_cache_reused_across_processes(self):
        """Criterion 2: the second load of a JIT kernel must hit the cache."""
        if not torch.cuda.is_available():
            self.skipTest("requires a CUDA device to load a JIT kernel")
        cache_dir = os.environ.get("TVM_FFI_CACHE_DIR", "~/.cache/tvm-ffi")
        print(f"tvm-ffi cache dir (default location): {os.path.expanduser(cache_dir)}")

        def _load_once(label: str) -> float:
            proc = subprocess.run(
                [sys.executable, "-c", _LOAD_KERNEL_SNIPPET],
                capture_output=True,
                text=True,
                timeout=900,
            )
            self.assertEqual(
                proc.returncode,
                0,
                f"{label} JIT kernel load failed:\n{proc.stderr[-2000:]}",
            )
            elapsed_line = [
                line
                for line in proc.stdout.splitlines()
                if line.startswith("JIT_LOAD_ELAPSED=")
            ]
            self.assertTrue(elapsed_line, f"{label}: no elapsed marker in output")
            return float(elapsed_line[-1].split("=")[1])

        first = _load_once("warm-up")
        second = _load_once("second")
        print(f"first load: {first:.2f}s, second load: {second:.2f}s")
        self.assertLess(
            second,
            WARM_LOAD_TIMEOUT_S,
            f"second JIT load took {second:.1f}s (> {WARM_LOAD_TIMEOUT_S}s): "
            "the NAS JIT cache is not being reused, nightly duration will "
            "silently regress (2026-07-22 RCA)",
        )


if __name__ == "__main__":
    unittest.main()
