#ifndef COMPATIBLE_WRAPPER_H
#define COMPATIBLE_WRAPPER_H

/*
 * compatible_wrapper.h — Compatibility layer for PPU
 *
 * Provides COMPATIBLE_XXX version macros, COMPATIBLE_ARCH define,
 * and compatibleXxx GetVersion API stubs for code converted by sailify.
 *
 * Generated by sailify with version config:
 *   CUDA: 13.0.0, cuBLAS: 13.0.0, cuFFT: 12.0.0,
 *   cuRAND: 10.4.0, cuSPARSE: 12.0.0, cuSOLVER: 12.0.3,
 *   cuDNN: 8.9.5, NCCL: 2.27.3,
 *   Video: 13.0.19, CUPTI: 130000, NPP: 13.0.50
 */

#include <hggc.h>
#include <stdio.h>
#include <stdlib.h>

/* PPU SDK fixups — must come before other PPU SDK headers */
#include "ppu_sdk_fixups.h"

/* PPU SDK headers — C++ only (pure C third-party code may conflict) */
#if defined(__cplusplus)

#include <acblas_v2.h>
#include <acdnn.h>
#include <acfft.h>
#include <acrand.h>
#include <acsolverDn.h>
#include <acsolver_common.h>
#include <acsparse.h>
#include <hgJitLink.h>
#include <hgTIXCompiler.h>
#include <hggc_library_types.h>
#include <hgml.h>
#include <hgppcore.h>
#include <hgppdefs.h>
#include <hgpti_checkpoint.h>
#include <hgpti_pcsampling_util.h>
#include <hgpti_result.h>
#include <hgrtc.h>

#endif /* __cplusplus */

/* PPU SDK fixups (post-include phase) */
#define PPU_SDK_FIXUPS_POST
#include "ppu_sdk_fixups.h"

/* ── Version macros ── */

#define COMPATIBLE_VERSION 13000
#define COMPATIBLE_RT_VERSION 13000
#define COMPATIBLE_DNN_VERSION 8905
#define COMPATIBLE_BLAS_VERSION 130000
#define COMPATIBLE_FFT_VERSION 12000
#define COMPATIBLE_RAND_VERSION 10400
#define COMPATIBLE_SPARSE_VERSION 12000
#define COMPATIBLE_SOLVER_VERSION 12003
#define COMPATIBLE_NCCL_VERSION 22703
#define COMPATIBLE_CUPTI_VERSION 130000
#define COMPATIBLE_VIDEO_VERSION 13019

#define COMPATIBLE_NPP_MAJOR 13
#define COMPATIBLE_NPP_MINOR 0
#define COMPATIBLE_NPP_BUILD 50

#define COMPATIBLE_DNN_MAJOR 8
#define COMPATIBLE_DNN_MINOR 9
#define COMPATIBLE_DNN_PATCHLEVEL 5

#define COMPATIBLE_BLAS_MAJOR 13
#define COMPATIBLE_BLAS_MINOR 0
#define COMPATIBLE_BLAS_PATCHLEVEL 0

#define COMPATIBLE_FFT_MAJOR 12
#define COMPATIBLE_FFT_MINOR 0
#define COMPATIBLE_FFT_PATCH 0

#define COMPATIBLE_RAND_MAJOR 10
#define COMPATIBLE_RAND_MINOR 4
#define COMPATIBLE_RAND_PATCH 0

#define COMPATIBLE_SPARSE_MAJOR 12
#define COMPATIBLE_SPARSE_MINOR 0
#define COMPATIBLE_SPARSE_PATCH 0

#define COMPATIBLE_SOLVER_MAJOR 12
#define COMPATIBLE_SOLVER_MINOR 0
#define COMPATIBLE_SOLVER_PATCH 3

#define COMPATIBLE_NCCL_MAJOR 2
#define COMPATIBLE_NCCL_MINOR 27
#define COMPATIBLE_NCCL_PATCH 3

#define COMPATIBLE_NCCL_VERSION_CALC(X, Y, Z) ((X) * 10000 + (Y) * 100 + (Z))

#define __COMPATIBLECC_VER_MAJOR__ 13
#define __COMPATIBLECC_VER_MINOR__ 0
#define __COMPATIBLECC_VER_BUILD__ 0

/* ── Architecture mapping ── */

/* COMPATIBLE_ARCH mirrors __CUDA_ARCH__: device-only.
 * Do NOT use __HGGCCC__ here — it's defined for all -x cu code. */
#if defined(__HGGC_ARCH__)
#ifndef COMPATIBLE_ARCH
#if __HGGC_ARCH__ == 100
#define COMPATIBLE_ARCH 800
#elif __HGGC_ARCH__ == 150
#define COMPATIBLE_ARCH 890
#else
#define COMPATIBLE_ARCH __HGGC_ARCH__
#endif
#endif
#endif

/* COMPATIBLE_ARCH_LIST mirrors __CUDA_ARCH_LIST__: only defined by hgcc,
 * not by plain g++. */
#ifndef COMPATIBLE_ARCH_LIST
#if defined(__HGGCCC__)
#if defined(COMPATIBLE_ARCH)
#define COMPATIBLE_ARCH_LIST COMPATIBLE_ARCH
#else
#define COMPATIBLE_ARCH_LIST 800
#endif
#endif
#endif

/* ── GetVersion API stubs ── */

#if defined(__cplusplus)

#ifdef __cplusplus
extern "C" {
#endif

static inline hggcError_t compatibleDriverGetVersion(int *driverVersion) {
  if (driverVersion)
    *driverVersion = COMPATIBLE_VERSION;
  return (hggcError_t)0;
}

static inline hggcError_t compatibleRuntimeGetVersion(int *runtimeVersion) {
  if (runtimeVersion)
    *runtimeVersion = COMPATIBLE_RT_VERSION;
  return (hggcError_t)0;
}

static inline acblasStatus_t compatibleBlasGetVersion(acblasHandle_t handle,
                                                      int *version) {
  (void)handle;
  if (version)
    *version = COMPATIBLE_BLAS_VERSION;
  return (acblasStatus_t)0;
}

static inline size_t compatibleBlasLtGetVersion(void) {
  return (size_t)COMPATIBLE_BLAS_VERSION;
}

static inline size_t compatibleBlasLtGetCudartVersion(void) {
  return (size_t)COMPATIBLE_VERSION;
}

static inline size_t compatibleDnnGetVersion(void) {
  return (size_t)COMPATIBLE_DNN_VERSION;
}

static inline size_t compatibleDnnGetCudartVersion(void) {
  return (size_t)COMPATIBLE_VERSION;
}

static inline hgrtcResult compatiblertcVersion(int *major, int *minor) {
  if (major)
    *major = COMPATIBLE_VERSION / 1000;
  if (minor)
    *minor = (COMPATIBLE_VERSION / 100) % 10;
  return (hgrtcResult)0;
}

static inline hgJitLinkResult compatibleJitLinkGetVersion(unsigned int *major,
                                                          unsigned int *minor) {
  if (major)
    *major = COMPATIBLE_VERSION / 1000;
  if (minor)
    *minor = (COMPATIBLE_VERSION / 100) % 10;
  return (hgJitLinkResult)0;
}

static inline hgTIXCompileResult
compatiblePTXCompilerGetVersion(unsigned int *major, unsigned int *minor) {
  if (major)
    *major = COMPATIBLE_VERSION / 1000;
  if (minor)
    *minor = (COMPATIBLE_VERSION / 100) % 10;
  return (hgTIXCompileResult)0;
}

static inline acrandStatus_t compatibleRandGetVersion(int *version) {
  if (version)
    *version = COMPATIBLE_RAND_VERSION;
  return (acrandStatus_t)0;
}

static inline acfftResult compatibleFftGetVersion(int *version) {
  if (version)
    *version = COMPATIBLE_FFT_VERSION;
  return (acfftResult)0;
}

static inline acsparseStatus_t
compatibleSparseGetVersion(acsparseHandle_t handle, int *version) {
  (void)handle;
  if (version)
    *version = COMPATIBLE_SPARSE_VERSION;
  return (acsparseStatus_t)0;
}

static inline acsolverStatus_t compatibleSolverGetVersion(int *version) {
  if (version)
    *version = COMPATIBLE_SOLVER_VERSION;
  return (acsolverStatus_t)0;
}

/* Macro so pcclResult_t resolves at point of use (pccl.h not included here) */
#define compatibleNcclGetVersion(v)                                            \
  ((void)((v) ? (void)(*(v) = COMPATIBLE_NCCL_VERSION) : (void)0),             \
   static_cast<pcclResult_t>(0))

static inline HGptiResult compatibleCuptiGetVersion(unsigned int *version) {
  if (version)
    *version = COMPATIBLE_CUPTI_VERSION;
  return (HGptiResult)0;
}

static inline int compatibleVideoGetVersion(unsigned int *version) {
  if (version)
    *version = COMPATIBLE_VIDEO_VERSION;
  return 0;
}

static inline const HGppLibraryVersion *compatiblePpGetLibVersion(void) {
  static const HGppLibraryVersion v = {
      COMPATIBLE_NPP_MAJOR,
      COMPATIBLE_NPP_MINOR,
      COMPATIBLE_NPP_BUILD,
  };
  return &v;
}

#ifdef __cplusplus
}
#endif

/* ── GetProperty API stubs ── */

#ifdef __cplusplus
extern "C" {
#endif

/* cuDNN/cuFFT/cuRAND/cuSPARSE/cuSOLVER: major*1000 + minor*100 + patch */
static inline int
_compatible_extract_property_std(int version, hggcLibraryPropertyType type) {
  if (type == HGGC_MAJOR_VERSION)
    return version / 1000;
  if (type == HGGC_MINOR_VERSION)
    return (version / 100) % 10;
  if (type == HGGC_PATCH_LEVEL)
    return version % 100;
  return 0;
}

/* cuBLAS: major*10000 + minor*100 + patch */
static inline int
_compatible_extract_property_cublas(int version, hggcLibraryPropertyType type) {
  if (type == HGGC_MAJOR_VERSION)
    return version / 10000;
  if (type == HGGC_MINOR_VERSION)
    return (version / 100) % 100;
  if (type == HGGC_PATCH_LEVEL)
    return version % 100;
  return 0;
}

static inline acdnnStatus_t
compatibleDnnGetProperty(hggcLibraryPropertyType type, int *value) {
  if (value)
    *value = _compatible_extract_property_std(COMPATIBLE_DNN_VERSION, type);
  return (acdnnStatus_t)0;
}

static inline acblasStatus_t
compatibleBlasGetProperty(hggcLibraryPropertyType type, int *value) {
  if (value)
    *value = _compatible_extract_property_cublas(COMPATIBLE_BLAS_VERSION, type);
  return (acblasStatus_t)0;
}

static inline acfftResult compatibleFftGetProperty(hggcLibraryPropertyType type,
                                                   int *value) {
  if (value)
    *value = _compatible_extract_property_std(COMPATIBLE_FFT_VERSION, type);
  return (acfftResult)0;
}

static inline acrandStatus_t
compatibleRandGetProperty(hggcLibraryPropertyType type, int *value) {
  if (value)
    *value = _compatible_extract_property_std(COMPATIBLE_RAND_VERSION, type);
  return (acrandStatus_t)0;
}

static inline acsolverStatus_t
compatibleSolverGetProperty(hggcLibraryPropertyType type, int *value) {
  if (value)
    *value = _compatible_extract_property_std(COMPATIBLE_SOLVER_VERSION, type);
  return (acsolverStatus_t)0;
}

/* ── Unsupported API stubs (auto-generated) ── */
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
#include "ppu_unsupported_stubs.h"
#pragma GCC diagnostic pop
#ifdef __cplusplus
}
#endif

#endif /* __cplusplus */

#endif /* COMPATIBLE_WRAPPER_H */
